image: docker/compose:1.27.4
services:
  - docker:18.09.9-dind

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - build
  - test
  - release

lint_dockerfile:
  image: hadolint/hadolint:latest-debian
  stage: lint
  script:
    - hadolint image/Dockerfile


build:
  artifacts:
    untracked: true
  script: timeout 1440 sh -x ./build.sh --build
  stage: build
  tags:
    - docker
    
test:
  artifacts:
    untracked: true
  dependencies:
    - build
  script: timeout 1440 sh -x ./build.sh --test
  stage: test
  tags:
    - docker

release:
  artifacts:
    untracked: true
  only:
    - tags
    - triggers
  script: timeout 1440 sh -x ./build.sh --release
  stage: release
  tags:
    - docker
