image: docker/compose:1.29.2
services:
  - docker:20.10.9-dind

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - build
  - test
  - release

lint_dockerfile:
  image: hadolint/hadolint:v1.23.0-1-ga556eaf-debian
  stage: lint
  script:
    - hadolint image/Dockerfile
    
shell check:
  image: koalaman/shellcheck-alpine:v0.7.2
  stage: lint
  script:
    - find image \( -name "*.sh" -o -name "*.bash" \) -print0 | xargs --no-run-if-empty -0 shellcheck

build:
  artifacts:
    untracked: true
  script: timeout 1440 sh -x ./build.sh --build
  stage: build
  tags:
    - docker
    
test:
  artifacts:
    untracked: true
  dependencies:
    - build
  script: timeout 1440 sh -x ./build.sh --test
  stage: test
  tags:
    - docker

release:
  artifacts:
    untracked: true
  dependencies:
    - test
  only:
    - tags
    - triggers
  script: timeout 1440 sh -x ./build.sh --release
  stage: release
  tags:
    - docker
