image: docker/compose:1.25.5
services:
  - docker:18.09.9-dind

variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk add --no-cache openssl curl

stages:
  - build
  - test
  - release

build:
  artifacts:
    untracked: true
  script: timeout 1440 sh -x ./build.sh --build
  stage: build
  tags:
    - docker
    
test:
  artifacts:
    untracked: true
  dependencies:
    - build
  script: timeout 1440 sh -x ./build.sh --test
  stage: test
  tags:
    - docker

release:
  artifacts:
    untracked: true
  only:
    - tags
    - triggers
  script: timeout 1440 sh -x ./build.sh --release
  stage: release
  tags:
    - docker
