VLO_VERSION="4.8.2-SNAPSHOT"
REMOTE_RELEASE_URL="file:/Users/twagoo/git/VLO/vlo-distribution/target/vlo-${VLO_VERSION}-docker.tar.gz"
NAME="vlo-${VLO_VERSION}-docker"
VLO_DISTR_FILE="webapp/vlo-${VLO_VERSION}-docker.tar.gz"
VLO_DISTR_DIR="webapp/vlo"
