VLO_VERSION="4.7.0-beta1"
REMOTE_RELEASE_URL="https://github.com/clarin-eric/VLO/releases/download/${VLO_VERSION}/vlo-${VLO_VERSION}-docker.tar.gz"
NAME="vlo-${VLO_VERSION}-docker"
VLO_DISTR_FILE="webapp/vlo-${VLO_VERSION}-docker.tar.gz"
VLO_DISTR_DIR="webapp/vlo"
