= CLARIN vlo image (`docker-vlo`)
:caution-caption: â˜¡ CAUTION
:important-caption: â— IMPORTANT
:note-caption: ðŸ›ˆ NOTE
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:source-highlighter: pygments
:tip-caption: ðŸ’¡ TIP
:toc-placement: preamble
:toc:
:warning-caption: âš  WARNING

== Dependencies

[options="header",cols=",,,m"]
|===
| Conditions | Type | Name (URL) | Version constraint

| by necessity
| software
| https://www.docker.com/[Docker Compose]
| ==1.8.0

| by necessity
| software
| https://www.docker.com/[Docker Engine]
| ==1.12.1

| by necessity
| image
| https://github.com/gliderlabs/docker-alpine[`gliderlabs/alpine`]
| ==3.4

| for Docker Engine interaction
| software
| https://www.sudo.ws/[Sudo]
| >=1.8

| for releases
| platform
| https://about.gitlab.[GitLab CI]
| ==8.10.4

|===

== To build and test

The build, test and release pipeline is specified in the the link:.gitlab-ci.yml[GitLab CI] config file.
This pipeline or its stages can be run by GitLab.com CI as well as by a self-hosted GitLab instance.
This is elaborated in the https://about.gitlab.com/gitlab-ci/[GitLab CI docs].
In addition, the build and test stages can be run be run locally within a bare Docker container, without a GitLab CI pipeline.

NOTE: Please issue all of the following shell statements from within the root directory of this repository.

=== Without a GitLab CI pipeline

[source,sh]
----
sh build.sh --local --build
----

=== Parameters

* `VLO_MAPPING_DEFINITIONS_DIST_URL`, specify the location of the tarball from which VLO mapping definitions are retrieved on startup and before import (leave empty to skip retrieval, e.g. when using a remote location - see below)
** for example: `https://github.com/clarin-eric/VLO-mapping/archive/beta.tar.gz`

[StatsD](https://github.com/etsy/statsd) parameters - not setting one of these will prevent statistics from being collected and sent after import:

* `STATSD_PREFIX`, specifiy an alternative statsd prefix when sending statistics
** for example: `vlo.beta`
* `VLO_DOCKER_STATSD_HOST`, StatsD host to send metrics to
** for example: `stats.domain.com`
* `VLO_DOCKER_STATSD_PORT`, StatsD port on host - defaults to 8125
** for example: 8125

Parameters that are used to filter VloConfig.xml:

* `VLO_DOCKER_SOLR_URL`, base URL for the Solr instance to be used by the importer and web app for connecting.
** for example: `http://vlo_solr:8983/solr/vlo-index/`
* `VLO_DOCKER_PUBLIC_HOME_URL`, public base URL of the web application. 
** for example: `http://beta-vlo.clarin.eu`
* `VLO_DOCKER_MAPPING_BASE_URI`, base URL (file or http) for retrieval of the VLO mapping files. 
** for example: `file:/srv/VLO-mapping/`
* `VLO_DOCKER_FILE_PROCESSING_THREADS`, number of file processing threads (number of CPU cores seems to be a good rule of thumb, or use -1 to let the VM decide based on the available number of cores)
** for example: `-1`
* `VLO_DOCKER_SOLR_THREADS`, number of Solr threads (0.5 to 1.0 times the number of file processing threads seems to be a good rule of thumb)
** for example: `2`
* `VLO_DOCKER_DELETE_ALL_FIRST`, a boolean determining whether the index should be cleaned at the start of import
** for example: `false`
* `VLO_DOCKER_MAX_DAYS_IN_SOLR`, number of days after which files that have disappeared should be removed from the index
** for example: `7`
* `VLO_DOCKER_DATAROOTS_FILE`, filename (absolute or relative to `VloConfig.xml`) that defines the data roots; this can be one of the shipped data root definitions or your own custom definition from a volume or mount
** for example: `dataroots-production.xml`
** or: `/srv/myconfig/dataroots.xml`
* 

These are to be passed as environment variables. The VloConfig.xml file gets filtered using these on container startup (see the `filter-vlo-config.sh` and `init.sh` scripts).
